version: '2'
services:
    farmer-app:
        image: farmer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=farmer-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    farmer-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: farmer-cassandra
    farmer-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=farmer-cassandra
    farmer-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: farmer-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
